

name: '[SCH] Quality Engineering'

on:
  schedule:
    - cron: '0 0/2 * 1/1 * ? *'

# http://www.cronmaker.com/;jsessionid=node01e2l7crw3jjj113bzdb4p69axc730842.node0?0
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            echo "Syed"
